# Generated by Django 5.0.4 on 2024-05-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
