# Generated by Django 5.0.4 on 2024-05-23 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biblioteca_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='id_bibliotecario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='libro',
            name='id_genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_api.genero'),
        ),
        migrations.AddField(
            model_name='detalleprestamo',
            name='id_libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalleprestamos', to='biblioteca_api.libro'),
        ),
        migrations.AddField(
            model_name='autor',
            name='id_nacionalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_api.nacionalidad'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='id_bibliotecario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='id_devolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca_api.devolucion'),
        ),
        migrations.AddField(
            model_name='detalleprestamo',
            name='id_prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalleprestamolibro', to='biblioteca_api.prestamo'),
        ),
        migrations.AddField(
            model_name='libro',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_api.proveedor'),
        ),
        migrations.AddField(
            model_name='publica',
            name='id_editorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_api.editorial'),
        ),
        migrations.AddField(
            model_name='publica',
            name='id_libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_api.libro'),
        ),
        migrations.AddField(
            model_name='usuariobiblioteca',
            name='id_bibliotecario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamo', to='biblioteca_api.usuariobiblioteca'),
        ),
    ]
