# Generated by Django 5.0.4 on 2024-05-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_api', '0003_prestamo_fecha_caducidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_caducidad',
            field=models.DateField(),
        ),
    ]
