# Generated by Django 5.0.4 on 2024-05-23 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_api', '0004_alter_prestamo_fecha_caducidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleprestamo',
            name='id_libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalleprestamos', to='biblioteca_api.libro'),
        ),
    ]
