# Generated by Django 5.0.4 on 2024-05-22 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_api', '0005_remove_usuariobiblioteca_id_bibliotecario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariobiblioteca',
            name='id_bibliotecario',
        ),
        migrations.AddField(
            model_name='usuariobiblioteca',
            name='id_bibliotecario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bibliotecario', to=settings.AUTH_USER_MODEL),
        ),
    ]
