# Generated by Django 5.0.4 on 2024-05-23 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_api', '0008_alter_detalleprestamo_id_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariobiblioteca',
            name='fecha_creacion',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 5, 23, 1, 3, 6, 196652)),
        ),
    ]
