# Generated by Django 5.0.4 on 2024-05-23 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_api', '0009_usuariobiblioteca_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamo', to='biblioteca_api.usuariobiblioteca'),
        ),
        migrations.AlterField(
            model_name='usuariobiblioteca',
            name='fecha_creacion',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
