# Generated by Django 5.0.4 on 2024-05-23 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_api', '0010_alter_prestamo_id_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleprestamo',
            name='id_prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalleprestamolibro', to='biblioteca_api.prestamo'),
        ),
    ]
