# Generated by Django 5.0.4 on 2024-05-23 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_api', '0005_alter_detalleprestamo_id_libro'),
        ('biblioteca_api', '0011_alter_detalleprestamo_id_prestamo'),
    ]

    operations = [
    ]
